### PR TITLE
moved the code to frontend library react

### PR DESCRIPTION
**Pull request by anugcodes**
moved the project to react.
created a landing page and dashboard route. 
the dashboard route currently has only tasks tab having function to add,delete,edit,search tasks.
this pr addressed the issue #12  .
i have used tailwindcss , formik and yum for form validation and react-icons .

### CODE REVIEW

**Comment by swarnavopramanik** [comment]
What type of change you it shown blank
Or you just start work  which one brother ??

**Comment by anugcodes** [comment]
hey it works in local machine, when type 'npm run dev'.

Annotation 2023-01-29 192637
<br/>
Annotation 2023-01-29 192715
<br/>
Annotation 2023-01-29 192743

**Comment by swarnavopramanik** [comment]
Okk very very sorry brother my exam start Tomorrow so I didn't look this in my laptop sorry yeahh yeahh sure react stat is npm run build or npm start 😊😊

**Comment by swarnavopramanik** [comment]
Great work 💯💯😍

**Comment by anugcodes** [comment]
no problem, i deployed the application on my netlify account. [link](https://helpful-alpaca-8f5ef6.netlify.app/)

**Comment by swarnavopramanik** [comment]
Great work brother 💯💯

**Comment by swarnavopramanik** [comment]
I will give you highest marks in this work 😊😊 
Please connect me linkdin after exam I will talk to you as a friend not work releted

**Comment by anugcodes** [comment]
Sure

**Comment by swarnavopramanik** [comment]
Great work I think totally work is complete right now , can you send deploy link please I can watch code letter....
I really appreciate that for work you are great...
And best wishes for you in your future 🙂😊😊

**Comment by swarnavopramanik** [comment]
@anugcodes in my computer when I am installing all dependencies and then start server it will start and front look is as same with your picture when you send ss but I am click get started it will not work but why for your case it will work why not work my case

**Comment by swarnavopramanik** [comment]
@anugcodes great work brother 💯💯
I really appreciate your work it so good looking then my project
I really thanks for making you hard working
😊❤️

**Pull request merged**
